apiVersion: v2
name: gateway-lens
description: A diagnostic dashboard for Kubernetes Gateway API resources.
type: application
version: 0.2.0
appVersion: "0.2.0"
home: https://github.com/nginxinc/gateway-lens
sources:
  - https://github.com/nginxinc/gateway-lens
keywords:
  - gateway
  - dashboard
  - kubernetes
